[FTP]
# Fast download with 4 parallel connections
# Useful for large directories with many small files
LOCAL_DIRECTORY = c:\ftp_backup
FTP_DIRECTORY = /remote/path
FTP_HOST = server.com
FTP_USER = user
FTP_PASS = password

DIRECTION = down
CONCURRENT_UPLOADS_OR_DOWNLOADS = 4
