[FTP]
LOCAL_DIRECTORY = c:\ftp_backup
FTP_DIRECTORY = /remote/path
FTP_HOST = server.com
FTP_USER = user
FTP_PASS = password

DIRECTION = down

CONCURRENT_UPLOADS_OR_DOWNLOADS = 1

# Delete files from FTP that are older than 90 days
DELETE_SOURCE_AFTER_DAYS = 90
