[FTP]
# Secure FTPS connection (FTP over TLS)
LOCAL_DIRECTORY = c:\secure_backup
FTP_DIRECTORY = /data
FTP_HOST = secure.server.com
FTP_USER = user
FTP_PASS = password

DIRECTION = down
TRANSFER_TYPE = FTPS
