[FTP]
# Simple upload: push a local folder to FTP
# Files deleted locally are also deleted from FTP
LOCAL_DIRECTORY = c:\my_website
FTP_DIRECTORY = /public_html
FTP_HOST = server.com
FTP_USER = user
FTP_PASS = password

DIRECTION = up
