[FTP]
# Upload while skipping specific directories
# Combine with a .deployignore file for fine-grained control
LOCAL_DIRECTORY = c:\my_website
FTP_DIRECTORY = /public_html
FTP_HOST = server.com
FTP_USER = user
FTP_PASS = password

DIRECTION = up
IGNORE_DIRS = node_modules, .git, __pycache__, tmp
